### PR TITLE
fix: put back navbar + footer

### LINKED ISSUE #65: [Fix]: Navbar/footer missing from singularity.storage homepage; broken links in navbar in other instance
**Description**
- The navbar and footer are missing from the singularity.storage homepage. It was there as recently as last week (Nov 21) when I was last on the site. I don't believe this was an intentional change as both are still visible at /signup

- Where instances of the navbar do exist (see /signup), links to "Features", "How it Works", and "Roadmap" are broken

**Reproduce**
1. Go to singularity.storage
1a. Observe missing navbar and footer on homepage
2.  Click on "Sign up" CTA
2a. Observe navbar and footer at /signup
3. Click on "Features" "How it works" and "Roadmap" nav links
3a. Observe lack of response

### PR DESCRIPTION
**Pull request by tikagan**
## Description

- [x] adds navbar and footer back to default page layout

## Ticket link

Ticket [AU-3057](vhttps://www.notion.so/agencyundone/AU-3057)

### CODE REVIEW

File: layouts/default.vue [hunk 1]
```diff
@@ -1,11 +1,11 @@
 <template>
   <div class="layout default" tabindex="-1">
 
-    <!-- <SiteHeader /> -->
```
Comment (orvn) [inline layouts/default.vue:4]: How strange that they just got commented out. Yeah, let's merge of course.

**Review by orvn — APPROVED** [review]
